# Generated by Django 4.2.2 on 2023-06-19 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shops.customer'),
        ),
    ]
