# Generated by Django 4.2.2 on 2023-06-19 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_product_prod_active_alter_product_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prod_active',
            new_name='product_active',
        ),
    ]
