# Generated by Django 4.2.2 on 2023-06-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_rename_prod_active_product_product_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
        ),
    ]
