# Generated by Django 4.2.2 on 2023-06-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_remove_customer_password_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
